import java.util.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.math.*;

/*
 * Problem:
 * Consider all integer combinations of a^b for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:
 * 2^2=4, 2^3=8, 2^4=16, 2^5=32
 * 3^2=9, 3^3=27, 3^4=81, 3^5=243
 * 4^2=16, 4^3=64, 4^4=256, 4^5=1024
 * 5^2=25, 5^3=125, 5^4=625, 5^5=3125
 * If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:
 * 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
 * How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
 * 
 * Solution: 669171001
 * Average Time: 0ms
 *
 * The corner numbers of each inner-square (1x1, 3x3, etc) follow a pattern. The first four are found by
 * adding 2 the previous, the next four are found by adding 4 to the previous. Then 6, then 8, and so on.
 * 
 * Uses IntegerAsString.java
 * 
 */

class Main {
	public static void main(String[] args) {
		long start = System.currentTimeMillis();
		double ans = 0;
		
		ArrayList<IntegerAsString> vals = new ArrayList<IntegerAsString>();
			
		for (int i = 2; i <= 100; i++)
			for (int ii = 2; ii <= 100; ii++) {
				IntegerAsString alma = new IntegerAsString(IntegerAsString.pow(i, ii));
				//System.out.println(i + "^" + ii);
				if (!contains(alma, vals)) vals.add(alma);
			}
		
		ans = vals.size();

		long end = System.currentTimeMillis() - start;
		System.out.printf("%f\n", ans);
		System.out.println(end);
	}
	
	public static boolean contains(IntegerAsString x, ArrayList<IntegerAsString> nums) {
		for (int i = 0; i < nums.size(); i++) if (nums.get(i).equals(x)) return true;
		return false;
	}
}
