import java.util.*;

/*
 * Problem:
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * 
 * Solution: 4613732
 * Average Time: 0ms
 * 
 * Creates fibonacci numbers and adds them to a list. 
 * Then, loops through the list and if the number is even, it is added to a sum
 */

class Main {
	public static void main(String[] args) {
		long start = System.currentTimeMillis();
		double ans = 0;
		ArrayList<Integer> fib = new ArrayList<Integer>();
		int i = 1;
		fib.add(1);
		fib.add(1);
		// System.out.println("chkpt");
		while (i < 4000000) {
			// System.out.println("chkpt1");
			fib.add(fib.get(fib.size() - 1) + fib.get(fib.size() - 2));
			i = fib.get(fib.size() - 1);
			if (i > 4000000)
				fib.remove(fib.size() - 1);
		}

		for (int x = 0; x < fib.size(); x++) {
			if (fib.get(x) % 2 == 0)
				ans += fib.get(x);
		}
		long end = System.currentTimeMillis() - start;
		System.out.println(ans);
		System.out.println(end);
	}
}
