from time import time

st = time()

n0 = n1 = 1; n2 = 0
total = 0
while(n2 < 4000000):
    n2 = n0 + n1
    n0 = n1 
    n1 = n2

    if n2 % 2 == 0:
        total += n2

print(total)
print(f"Time taken : {time() - st}")
#Avg Time Taken: 9.9E-4 seconds

# Problem:
    # Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
    # By starting with 1 and 2, the first 10 terms will be:
        # 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    # By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# Solution:
    # The three variables n0,n1,n2 represent consecutive terms in the fibonacci sequence.
    # The next term (n2) is the prev two terms added together.
    # I check if n2 is even, and add it to the sum if it is.
    # Then shuffle all the terms back so I can generate the next term in the sequence.
    # Repeat while the next term is less than 4 million.